services:
#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     networks:
#       - app-network

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - ./server:/app/server
      - ./server/package.json:/app/server/package.json
      - ./server/bun.lockb:/app/server/bun.lockb
    ports:
      - "8585:8585"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_ATLAS_USERNAME: ${MONGO_ATLAS_USERNAME}
      MONGO_ATLAS_PASSWORD: ${MONGO_ATLAS_PASSWORD}

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app/client
      - ./client/package.json:/app/client/package.json
    ports:
      - "9595:9595"
    networks:
      - app-network

# volumes:
#   mongo-data:

networks:
  app-network:
