services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/tmp/portfolio/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8585:8585"
    networks:
      - app-network
    volumes:
      - db-data:/tmp/portfolio/db

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "9595:9595"
    networks:
      - app-networ    
    volumes:
      - mongo-data:/tmp/portfolio/db

volumes:
  mongo-data:

networks:
  app-network:
