name: Portfolio pipeline (pp)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build
      continue-on-error: true

    - name: Install node
      uses: actions/setup-node@v1
      continue-on-error: true

    - name: Install dependencies
      run: npm install
      continue-on-error: true

    - name: Run tests
      run: npm run test
      continue-on-error: true
      
    - name: Run coverage
      run: npm run coverage
      continue-on-error: true

    - name: Build app
      run: npm build
      continue-on-error: true
      
    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down
